package config

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strconv"

	"github.com/nqode/qode/internal/iokit"
	"gopkg.in/yaml.v3"
)

// devVersion is the version string carried by locally installed builds. It mirrors
// the skips in cli.checkVersion (root.go) and version.CheckCompatibility: a dev
// build does not participate in version enforcement, and Upgrade does not re-stamp
// qode_version for one either.
const devVersion = "dev"

// configFileMode is the permission for qode.yaml. It is committed and team-readable,
// so 0644 rather than the 0600 used for prompt scratch files.
const configFileMode = 0644

// ErrConfigExists is returned when qode.yaml already exists and overwrite is false.
var ErrConfigExists = errors.New("qode.yaml already exists")

// ErrConfigInvalid is returned when the project qode.yaml cannot be parsed or fails
// Validate. Only Upgrade returns it, so the CLI can attach the overwrite hint to a
// broken project file without attaching it to a broken .qode/scoring.yaml.
var ErrConfigInvalid = errors.New("invalid qode.yaml")

// WriteDefault renders the commented default document and writes it to root/qode.yaml.
// When overwrite is false an existing file is left untouched and ErrConfigExists is
// returned. The write is atomic because every subsequent workflow step reads this file.
func WriteDefault(ctx context.Context, root, binaryVersion string, overwrite bool) error {
	path := filepath.Join(root, ConfigFileName)
	if !overwrite {
		switch _, err := os.Stat(path); {
		case err == nil:
			return fmt.Errorf("%s: %w", path, ErrConfigExists)
		case !errors.Is(err, fs.ErrNotExist):
			return fmt.Errorf("checking %s: %w", path, err)
		}
	}
	data, err := encodeDocument(defaultDocument(binaryVersion))
	if err != nil {
		return err
	}
	if err := iokit.AtomicWriteCtx(ctx, path, data, configFileMode); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// encodeDocument renders a node tree at two-space indent, matching every YAML
// example in docs/qode-yaml-reference.md (yaml.v3 defaults to four).
func encodeDocument(n *yaml.Node) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(n); err != nil {
		_ = enc.Close()
		return nil, fmt.Errorf("encoding %s: %w", ConfigFileName, err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("encoding %s: %w", ConfigFileName, err)
	}
	return buf.Bytes(), nil
}

// rubricTotal sums the dimension weights of a default rubric so the generated
// comments cannot drift from DefaultRubricConfigs(). An unknown name yields the
// zero RubricConfig and a total of 0 rather than a panic.
func rubricTotal(name string) int {
	total := 0
	for _, d := range DefaultRubricConfigs()[name].Dimensions {
		total += d.Weight
	}
	return total
}

// scalarNode builds an untagged scalar so yaml.v3 infers the type from the literal
// text. qode_version is the one caller that overrides Tag.
func scalarNode(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Value: value}
}

func mappingNode(content ...*yaml.Node) *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode, Content: content}
}

// appendSection appends a commented key/value pair to a mapping node. The head
// comment starts with "\n" to render a blank separator line above the section.
func appendSection(m *yaml.Node, key, headComment string, value *yaml.Node) {
	k := scalarNode(key)
	k.HeadComment = headComment
	m.Content = append(m.Content, k, value)
}

// defaultDocument builds the fully commented default qode.yaml as a yaml.Node tree.
// It is the single source of truth for what qode.yaml contains: WriteDefault renders
// it and Upgrade uses it as the source of keys a file is missing.
// Comment text is lifted from docs/qode-yaml-reference.md.
func defaultDocument(binaryVersion string) *yaml.Node {
	def := DefaultConfig()
	if binaryVersion == "" {
		binaryVersion = devVersion
	}

	versionKey := scalarNode("qode_version")
	versionKey.HeadComment = "qode configuration. Full reference:\ndocs/qode-yaml-reference.md"
	versionVal := scalarNode(binaryVersion)
	versionVal.Tag = "!!str" // keeps a numeric-looking version quoted rather than a float
	versionVal.LineComment = "written by qode init; identifies the config format version"

	root := mappingNode(versionKey, versionVal)
	appendSection(root, "review", "\nMinimum scores a review must reach.", reviewNode(def.Review))
	appendSection(root, "scoring", "\nScoring engine. Rubric dimensions live in .qode/scoring.yaml, not here.", scoringNode(def.Scoring))
	appendSection(root, "ide", "\nIDE assets generated by 'qode init'. Set false to skip one.", ideNode(def.IDE))
	appendSection(root, "knowledge", "\nWhere 'qode knowledge' stores and looks up entries.", knowledgeNode(def.Knowledge))
	appendSection(root, "diff", "\nCommand whose stdout is the diff reviewed by 'qode review'.", diffNode(def.Diff))

	return &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}
}

// reviewNode renders the thresholds with one decimal so the generated file reads
// exactly like docs/qode-yaml-reference.md. The rubric maxima are derived, never
// typed: review totals 12 and security totals 10, and they are not the same number,
// so one shared comment would ship a false claim about min_security_score.
func reviewNode(r ReviewConfig) *yaml.Node {
	code := scalarNode(strconv.FormatFloat(r.MinCodeScore, 'f', 1, 64))
	code.LineComment = fmt.Sprintf("default review rubric total is %d", rubricTotal("review"))
	sec := scalarNode(strconv.FormatFloat(r.MinSecurityScore, 'f', 1, 64))
	sec.LineComment = fmt.Sprintf("default security rubric total is %d", rubricTotal("security"))
	return mappingNode(
		scalarNode("min_code_score"), code,
		scalarNode("min_security_score"), sec,
	)
}

// scoringNode carries target_score as a commented-out line rather than a live key:
// 0 is the sentinel for "use the refine rubric total", so an emitted 0 would be
// wrong and an emitted 25 would freeze a derived default. The comment hangs off the
// strict KEY node — a FootComment on the scoring mapping renders at column 0 after
// the next key.
func scoringNode(s ScoringConfig) *yaml.Node {
	strictKey := scalarNode("strict")
	strictKey.HeadComment = fmt.Sprintf(
		"target_score: %d # override the /qode-plan-refine pass threshold", rubricTotal("refine"))
	strictVal := scalarNode(strconv.FormatBool(s.Strict))
	strictVal.LineComment = "enforce step ordering; exit 1 when a gate fails"
	return mappingNode(strictKey, strictVal)
}

func ideNode(i IDEConfig) *yaml.Node {
	return mappingNode(
		scalarNode("cursor"), enabledNode(i.Cursor.Enabled, ".cursor/commands/*.mdc"),
		scalarNode("claude_code"), enabledNode(i.ClaudeCode.Enabled, ".claude/commands/*.md"),
		scalarNode("codex"), enabledNode(i.Codex.Enabled, ".agents/skills/*/SKILL.md"),
		scalarNode("opencode"), enabledNode(i.OpenCode.Enabled, ".opencode/commands/*.md"),
	)
}

// enabledNode labels each toggle with the assets it controls.
func enabledNode(enabled bool, assets string) *yaml.Node {
	v := scalarNode(strconv.FormatBool(enabled))
	v.LineComment = assets
	return mappingNode(scalarNode("enabled"), v)
}

func knowledgeNode(k KnowledgeConfig) *yaml.Node {
	return mappingNode(scalarNode("path"), scalarNode(k.Path))
}

// diffNode quotes the command: it round-trips unquoted too, but the reference doc
// and this repo's qode.yaml show it quoted, and a quoted string is the safer
// example for a user who edits it.
func diffNode(d DiffConfig) *yaml.Node {
	cmd := scalarNode(d.Command)
	cmd.Style = yaml.DoubleQuotedStyle
	return mappingNode(scalarNode("command"), cmd)
}

// Upgrade preserves an existing qode.yaml: every value the user set is kept,
// qode_version is re-stamped on release binaries, and settings the file is missing
// are appended with their defaults and their comments. It reports whether anything
// was written; when nothing changed the file's bytes and mtime are untouched.
// A file that cannot be parsed or fails Validate is left alone and reported as
// ErrConfigInvalid.
func Upgrade(ctx context.Context, root, binaryVersion string) (bool, error) {
	path := filepath.Join(root, ConfigFileName)
	data, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("reading %s: %w", path, err)
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return false, fmt.Errorf("%w: parsing %s: %v", ErrConfigInvalid, path, err)
	}
	// An empty or comment-only file unmarshals to Kind 0 with no Content, which can
	// be neither decoded nor encoded. Both fields must be set, not just Content.
	if doc.Kind == 0 {
		doc.Kind = yaml.DocumentNode
		doc.Content = []*yaml.Node{{Kind: yaml.MappingNode}}
	}
	if err := validateDocument(&doc, path); err != nil {
		return false, err
	}
	rootNode := doc.Content[0]
	changed := mergeMissing(rootNode, defaultDocument(binaryVersion).Content[0])
	if stampVersion(rootNode, binaryVersion) {
		changed = true
	}
	if !changed {
		return false, nil
	}
	return true, writeDocument(ctx, path, &doc)
}

// validateDocument decodes the project file alone onto the defaults and validates it.
// Node.Decode onto a pre-populated struct merges key-by-key exactly like
// mergeFromFile, so this reproduces Load's project-file semantics without reading
// .qode/scoring.yaml or ~/.qode/config.yaml.
func validateDocument(doc *yaml.Node, path string) error {
	cfg := DefaultConfig()
	if err := doc.Decode(&cfg); err != nil {
		return fmt.Errorf("%w: parsing %s: %v", ErrConfigInvalid, path, err)
	}
	if err := cfg.Validate(); err != nil {
		return fmt.Errorf("%w: %s: %v", ErrConfigInvalid, path, err)
	}
	return nil
}

// mergeMissing appends to dst every (key, value) pair present in def but absent from
// dst, recursing into mappings the two share. A key dst already has is never read,
// rewritten or re-marshalled — that single rule is what preserves enabled: false,
// scoring.strict: true and any threshold the user tuned. Comments therefore arrive
// only with keys that are added.
func mergeMissing(dst, def *yaml.Node) bool {
	if dst.Kind != yaml.MappingNode || def.Kind != yaml.MappingNode {
		return false
	}
	changed := false
	for i := 0; i+1 < len(def.Content); i += 2 {
		defKey, defVal := def.Content[i], def.Content[i+1]
		dstVal := lookupValue(dst, defKey.Value)
		switch {
		case dstVal == nil:
			dst.Content = append(dst.Content, defKey, defVal)
			changed = true
		case dstVal.Kind == yaml.MappingNode && defVal.Kind == yaml.MappingNode:
			if mergeMissing(dstVal, defVal) {
				changed = true
			}
		}
	}
	return changed
}

// lookupValue returns the value node for key in a mapping node, or nil.
func lookupValue(m *yaml.Node, key string) *yaml.Node {
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i+1]
		}
	}
	return nil
}

// stampVersion refreshes qode_version for release binaries only. A dev build never
// overwrites an existing value, mirroring the skips in cli.checkVersion and
// version.CheckCompatibility, which is what keeps a tracked qode_version stable
// under 'go install' builds. A file missing the key entirely still gets it from
// mergeMissing (dev value included), because checkVersion treats an absent
// qode_version as not-initialised.
func stampVersion(root *yaml.Node, binaryVersion string) bool {
	if binaryVersion == "" || binaryVersion == devVersion {
		return false
	}
	v := lookupValue(root, "qode_version")
	if v == nil || v.Value == binaryVersion {
		return false
	}
	v.Value = binaryVersion
	v.Tag = "!!str"
	return true
}

// writeDocument renders doc and writes it atomically. A symlinked qode.yaml is
// resolved first so a shared config is written through rather than replaced by a
// regular file (os.Rename would swap the link itself).
func writeDocument(ctx context.Context, path string, doc *yaml.Node) error {
	out, err := encodeDocument(doc)
	if err != nil {
		return err
	}
	target, err := filepath.EvalSymlinks(path)
	if err != nil {
		return fmt.Errorf("resolving %s: %w", path, err)
	}
	if err := iokit.AtomicWriteCtx(ctx, target, out, configFileMode); err != nil {
		return fmt.Errorf("writing %s: %w", target, err)
	}
	return nil
}
