package config

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"runtime"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// writeDefaultInto renders the default document into a fresh directory and returns
// the directory and the bytes on disk.
func writeDefaultInto(t *testing.T, binaryVersion string) (string, []byte) {
	t.Helper()
	dir := t.TempDir()
	if err := WriteDefault(context.Background(), dir, binaryVersion, false); err != nil {
		t.Fatalf("WriteDefault: %v", err)
	}
	return dir, readConfig(t, dir)
}

func readConfig(t *testing.T, dir string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, ConfigFileName))
	if err != nil {
		t.Fatalf("reading %s: %v", ConfigFileName, err)
	}
	return data
}

func seedConfig(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, ConfigFileName), []byte(body), 0644); err != nil {
		t.Fatalf("seeding %s: %v", ConfigFileName, err)
	}
	return dir
}

func TestWriteDefault_RoundTripsToDefaultConfig(t *testing.T) {
	t.Parallel()

	_, data := writeDefaultInto(t, "0.4.0-beta")

	var got Config
	if err := yaml.Unmarshal(data, &got); err != nil {
		t.Fatalf("unmarshalling generated config: %v", err)
	}

	want := DefaultConfig()
	// Rubrics live in .qode/scoring.yaml, never in qode.yaml.
	want.Scoring.Rubrics = nil
	want.QodeVersion = "0.4.0-beta"

	if !reflect.DeepEqual(got, want) {
		t.Errorf("generated config does not round-trip to the defaults:\ngot  %+v\nwant %+v", got, want)
	}
}

// collectYAMLKeys gathers the yaml tag of every field reachable from typ.
func collectYAMLKeys(t *testing.T, typ reflect.Type, out map[string]struct{}) {
	t.Helper()
	for i := 0; i < typ.NumField(); i++ {
		f := typ.Field(i)
		tag, _, _ := strings.Cut(f.Tag.Get("yaml"), ",")
		if tag == "" || tag == "-" {
			continue
		}
		// Rubric dimensions live in .qode/scoring.yaml, never in qode.yaml, so the
		// walk stops here instead of descending into RubricConfig/DimensionConfig.
		if tag == "rubrics" {
			continue
		}
		out[tag] = struct{}{}
		if f.Type.Kind() == reflect.Struct {
			collectYAMLKeys(t, f.Type, out)
		}
	}
}

func TestWriteDefault_CoversEveryConfigKey(t *testing.T) {
	t.Parallel()

	_, data := writeDefaultInto(t, "")
	rendered := string(data)

	keys := map[string]struct{}{}
	collectYAMLKeys(t, reflect.TypeOf(Config{}), keys)
	if len(keys) < 10 {
		t.Fatalf("key walk collected only %d keys, expected the full schema", len(keys))
	}

	for key := range keys {
		// Match the key as a YAML key — active or commented out — so comment prose
		// that happens to contain the word cannot satisfy the assertion.
		pattern := regexp.MustCompile(`(?m)^\s*(#\s*)?` + regexp.QuoteMeta(key) + `:`)
		if !pattern.MatchString(rendered) {
			t.Errorf("generated qode.yaml has no %q key, active or commented", key)
		}
	}
}

func TestWriteDefault_IsCommented(t *testing.T) {
	t.Parallel()

	// Guard against a vacuous assertion: the comments below are derived from these
	// totals, and the three rubrics do not share a maximum.
	if got := rubricTotal("review"); got != 12 {
		t.Fatalf("review rubric total = %d, want 12", got)
	}
	if got := rubricTotal("security"); got != 10 {
		t.Fatalf("security rubric total = %d, want 10", got)
	}
	if got := rubricTotal("refine"); got != 25 {
		t.Fatalf("refine rubric total = %d, want 25", got)
	}

	_, data := writeDefaultInto(t, "")
	rendered := string(data)

	for _, want := range []string{
		"# qode configuration. Full reference:",
		"# docs/qode-yaml-reference.md",
		"written by qode init; identifies the config format version",
		"# Minimum scores a review must reach.",
		"default review rubric total is 12",
		"default security rubric total is 10",
		"# Scoring engine. Rubric dimensions live in .qode/scoring.yaml, not here.",
		"# target_score: 25 # override the /qode-plan-refine pass threshold",
		"enforce step ordering; exit 1 when a gate fails",
		"# IDE assets generated by 'qode init'. Set false to skip one.",
		".cursor/commands/*.mdc",
		".claude/commands/*.md",
		".agents/skills/*/SKILL.md",
		".opencode/commands/*.md",
		"# Where 'qode knowledge' stores and looks up entries.",
		"# Command whose stdout is the diff reviewed by 'qode review'.",
	} {
		if !strings.Contains(rendered, want) {
			t.Errorf("generated qode.yaml is missing comment %q", want)
		}
	}

	// The ambiguous shared wording would be a false claim about min_security_score.
	if strings.Contains(rendered, "default rubric total is 12") {
		t.Error("generated qode.yaml uses the ambiguous shared rubric comment")
	}

	scoringAt := strings.Index(rendered, "\nscoring:")
	targetAt := strings.Index(rendered, "# target_score:")
	strictAt := strings.Index(rendered, "strict:")
	if scoringAt < 0 || targetAt < scoringAt || strictAt < targetAt {
		t.Errorf("commented target_score is not inside the scoring block above strict (scoring=%d target=%d strict=%d)",
			scoringAt, targetAt, strictAt)
	}
}

func TestWriteDefault_ThenUpgradeIsNoOp(t *testing.T) {
	t.Parallel()

	dir, before := writeDefaultInto(t, "0.4.0-beta")

	changed, err := Upgrade(context.Background(), dir, "0.4.0-beta")
	if err != nil {
		t.Fatalf("Upgrade: %v", err)
	}
	if changed {
		t.Error("Upgrade rewrote a freshly generated config")
	}
	if got := readConfig(t, dir); string(got) != string(before) {
		t.Errorf("generated config changed:\n%s", got)
	}
}

func TestWriteDefault_ExistingFile(t *testing.T) {
	t.Parallel()

	const existing = "qode_version: 0.1.0\n"

	tests := []struct {
		name      string
		overwrite bool
		wantErr   error
		wantKept  bool
	}{
		{name: "refuses without overwrite", overwrite: false, wantErr: ErrConfigExists, wantKept: true},
		{name: "replaces with overwrite", overwrite: true},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			dir := seedConfig(t, existing)
			err := WriteDefault(context.Background(), dir, "0.4.0-beta", tc.overwrite)
			if !errors.Is(err, tc.wantErr) {
				t.Fatalf("WriteDefault error = %v, want %v", err, tc.wantErr)
			}

			got := string(readConfig(t, dir))
			if tc.wantKept {
				if got != existing {
					t.Errorf("existing file was modified: %q", got)
				}
				return
			}
			if !strings.Contains(got, "# Minimum scores a review must reach.") {
				t.Errorf("file was not replaced by the commented defaults:\n%s", got)
			}
		})
	}
}

func TestWriteDefault_UnwritableDirectory(t *testing.T) {
	t.Parallel()

	if runtime.GOOS == "windows" {
		t.Skip("directory permissions are not enforced the same way on Windows")
	}
	if os.Geteuid() == 0 {
		t.Skip("root ignores directory permissions")
	}

	dir := t.TempDir()
	if err := os.Chmod(dir, 0555); err != nil {
		t.Fatalf("chmod: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(dir, 0755) })

	err := WriteDefault(context.Background(), dir, "", true)
	if err == nil {
		t.Fatal("expected WriteDefault to fail in an unwritable directory")
	}
	if !strings.Contains(err.Error(), "create temp") {
		t.Errorf("error %v does not name the failed temp file creation", err)
	}
}

func TestUpgrade_PreservesUserValues(t *testing.T) {
	t.Parallel()

	dir := seedConfig(t, `# keep me
qode_version: 0.1.0
review:
  min_security_score: 10
scoring:
  strict: true
ide:
  cursor:
    enabled: false
`)

	changed, err := Upgrade(context.Background(), dir, "dev")
	if err != nil {
		t.Fatalf("Upgrade: %v", err)
	}
	if !changed {
		t.Fatal("Upgrade reported no change on a file missing several keys")
	}

	rendered := string(readConfig(t, dir))
	if !strings.Contains(rendered, "# keep me") {
		t.Errorf("hand-written comment was dropped:\n%s", rendered)
	}

	var got Config
	if err := yaml.Unmarshal([]byte(rendered), &got); err != nil {
		t.Fatalf("unmarshalling upgraded config: %v", err)
	}
	if got.Review.MinSecurityScore != 10 {
		t.Errorf("min_security_score = %v, want 10", got.Review.MinSecurityScore)
	}
	if !got.Scoring.Strict {
		t.Error("scoring.strict was reset to false")
	}
	if got.IDE.Cursor.Enabled {
		t.Error("ide.cursor.enabled was reset to true")
	}
	if got.QodeVersion != "0.1.0" {
		t.Errorf("qode_version = %q, want it left at 0.1.0 by a dev build", got.QodeVersion)
	}
}

func TestUpgrade_AppendsMissingKeys(t *testing.T) {
	t.Parallel()

	dir := seedConfig(t, `qode_version: 0.1.0
ide:
  cursor:
    enabled: true
`)

	if _, err := Upgrade(context.Background(), dir, "dev"); err != nil {
		t.Fatalf("Upgrade: %v", err)
	}

	rendered := string(readConfig(t, dir))
	if !strings.Contains(rendered, "  opencode:\n    enabled: true # .opencode/commands/*.md") {
		t.Errorf("opencode was not appended under the existing ide mapping with its comment:\n%s", rendered)
	}

	var got Config
	if err := yaml.Unmarshal([]byte(rendered), &got); err != nil {
		t.Fatalf("unmarshalling upgraded config: %v", err)
	}
	if !got.IDE.OpenCode.Enabled {
		t.Error("ide.opencode.enabled was not added")
	}
	if got.Knowledge.Path != ".qode/knowledge" {
		t.Errorf("knowledge.path = %q, want the appended default", got.Knowledge.Path)
	}
}

func TestUpgrade_VersionStamping(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name          string
		seedVersion   string
		binaryVersion string
		wantChanged   bool
		wantLine      string
	}{
		{name: "empty binary version leaves it alone", seedVersion: "0.1.0", binaryVersion: "", wantLine: "qode_version: 0.1.0"},
		{name: "dev binary leaves it alone", seedVersion: "0.1.0", binaryVersion: "dev", wantLine: "qode_version: 0.1.0"},
		{name: "missing key is added by a dev binary", binaryVersion: "dev", wantChanged: true, wantLine: "qode_version: dev"},
		{name: "release binary re-stamps", seedVersion: "0.1.0", binaryVersion: "0.4.0-beta", wantChanged: true, wantLine: "qode_version: 0.4.0-beta"},
		{name: "numeric version stays a string", seedVersion: "0.1.0", binaryVersion: "1.0", wantChanged: true, wantLine: `qode_version: "1.0"`},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			seed := tc.seedVersion
			if seed == "" {
				seed = "0.0.0"
			}
			dir, data := writeDefaultInto(t, seed)
			if tc.seedVersion == "" {
				data = stripVersionKey(t, data)
				if err := os.WriteFile(filepath.Join(dir, ConfigFileName), data, 0644); err != nil {
					t.Fatalf("rewriting seed: %v", err)
				}
			}

			changed, err := Upgrade(context.Background(), dir, tc.binaryVersion)
			if err != nil {
				t.Fatalf("Upgrade: %v", err)
			}
			if changed != tc.wantChanged {
				t.Errorf("changed = %v, want %v", changed, tc.wantChanged)
			}
			if got := string(readConfig(t, dir)); !strings.Contains(got, tc.wantLine) {
				t.Errorf("upgraded config does not contain %q:\n%s", tc.wantLine, got)
			}
		})
	}
}

// stripVersionKey removes the qode_version line so a seed file lacks the key.
func stripVersionKey(t *testing.T, data []byte) []byte {
	t.Helper()
	var kept []string
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "qode_version:") {
			continue
		}
		kept = append(kept, line)
	}
	return []byte(strings.Join(kept, "\n"))
}

func TestUpgrade_SecondPassIsIdempotent(t *testing.T) {
	t.Parallel()

	dir := seedConfig(t, "qode_version: 0.1.0\n")

	if _, err := Upgrade(context.Background(), dir, "dev"); err != nil {
		t.Fatalf("first Upgrade: %v", err)
	}
	path := filepath.Join(dir, ConfigFileName)
	before := readConfig(t, dir)
	statBefore, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}

	changed, err := Upgrade(context.Background(), dir, "dev")
	if err != nil {
		t.Fatalf("second Upgrade: %v", err)
	}
	if changed {
		t.Error("second Upgrade reported a change")
	}
	if got := readConfig(t, dir); string(got) != string(before) {
		t.Errorf("second Upgrade rewrote the file:\n%s", got)
	}
	statAfter, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if !statAfter.ModTime().Equal(statBefore.ModTime()) {
		t.Error("second Upgrade touched the file's mtime")
	}
}

func TestUpgrade_FillsEmptyFile(t *testing.T) {
	t.Parallel()

	dir := seedConfig(t, "")

	changed, err := Upgrade(context.Background(), dir, "0.4.0-beta")
	if err != nil {
		t.Fatalf("Upgrade: %v", err)
	}
	if !changed {
		t.Fatal("Upgrade reported no change on an empty file")
	}

	reference := t.TempDir()
	if err := WriteDefault(context.Background(), reference, "0.4.0-beta", true); err != nil {
		t.Fatalf("WriteDefault: %v", err)
	}
	want, err := os.ReadFile(filepath.Join(reference, ConfigFileName))
	if err != nil {
		t.Fatalf("reading reference: %v", err)
	}
	if got := readConfig(t, dir); string(got) != string(want) {
		t.Errorf("filled empty file differs from the generated default:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestUpgrade_FillsCommentOnlyFile(t *testing.T) {
	t.Parallel()

	dir := seedConfig(t, "# hand-written\n")

	changed, err := Upgrade(context.Background(), dir, "dev")
	if err != nil {
		t.Fatalf("Upgrade: %v", err)
	}
	if !changed {
		t.Fatal("Upgrade reported no change on a comment-only file")
	}

	rendered := string(readConfig(t, dir))
	if !strings.Contains(rendered, "# Minimum scores a review must reach.") {
		t.Errorf("comment-only file was not filled with the defaults:\n%s", rendered)
	}
	// Documented loss: a comment-only file has no node to hang its comment on.
	if strings.Contains(rendered, "# hand-written") {
		t.Error("comment-only file unexpectedly kept its comment; update the CHANGELOG caveat")
	}
}

func TestUpgrade_InvalidFile(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		body string
	}{
		{name: "parse error", body: "scoring: [\n"},
		{name: "validate failure", body: "review:\n  min_code_score: -1\n"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			dir := seedConfig(t, tc.body)

			changed, err := Upgrade(context.Background(), dir, "0.4.0-beta")
			if !errors.Is(err, ErrConfigInvalid) {
				t.Fatalf("error = %v, want ErrConfigInvalid", err)
			}
			if changed {
				t.Error("Upgrade reported a change for an invalid file")
			}
			if got := string(readConfig(t, dir)); got != tc.body {
				t.Errorf("invalid file was modified:\ngot  %q\nwant %q", got, tc.body)
			}
		})
	}
}

func TestUpgrade_DoesNotPersistUserLevelOrRubrics(t *testing.T) {
	// t.Setenv forbids t.Parallel; the planted user-level config lives under HOME.
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("USERPROFILE", home)

	userCfg := filepath.Join(home, QodeDir, "config.yaml")
	if err := os.MkdirAll(filepath.Dir(userCfg), 0755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(userCfg, []byte("ide:\n  codex:\n    enabled: false\n"), 0644); err != nil {
		t.Fatalf("writing user config: %v", err)
	}

	dir := seedConfig(t, "qode_version: 0.1.0\n")
	scoringPath := filepath.Join(dir, QodeDir, ScoringFileName)
	if err := os.MkdirAll(filepath.Dir(scoringPath), 0755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	scoringData, err := yaml.Marshal(&ScoringFileConfig{Rubrics: DefaultRubricConfigs()})
	if err != nil {
		t.Fatalf("marshalling rubrics: %v", err)
	}
	if err := os.WriteFile(scoringPath, scoringData, 0644); err != nil {
		t.Fatalf("writing scoring file: %v", err)
	}

	if _, err := Upgrade(context.Background(), dir, "0.4.0-beta"); err != nil {
		t.Fatalf("Upgrade: %v", err)
	}

	rendered := string(readConfig(t, dir))
	if strings.Contains(rendered, "rubrics") {
		t.Errorf("rubric definitions leaked into qode.yaml:\n%s", rendered)
	}
	if strings.Contains(rendered, "enabled: false") {
		t.Errorf("user-level IDE override leaked into qode.yaml:\n%s", rendered)
	}
}

func TestUpgrade_FollowsSymlink(t *testing.T) {
	t.Parallel()

	if runtime.GOOS == "windows" {
		t.Skip("symlink creation needs elevation on Windows")
	}

	target := filepath.Join(t.TempDir(), "shared.yaml")
	if err := os.WriteFile(target, []byte("qode_version: 0.1.0\n"), 0644); err != nil {
		t.Fatalf("writing target: %v", err)
	}
	dir := t.TempDir()
	link := filepath.Join(dir, ConfigFileName)
	if err := os.Symlink(target, link); err != nil {
		t.Fatalf("symlink: %v", err)
	}

	if _, err := Upgrade(context.Background(), dir, "dev"); err != nil {
		t.Fatalf("Upgrade: %v", err)
	}

	info, err := os.Lstat(link)
	if err != nil {
		t.Fatalf("lstat: %v", err)
	}
	if info.Mode()&os.ModeSymlink == 0 {
		t.Error("symlink was replaced by a regular file")
	}
	got, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("reading target: %v", err)
	}
	if !strings.Contains(string(got), "opencode:") {
		t.Errorf("symlink target was not upgraded:\n%s", got)
	}
}

func TestUpgrade_PreservesMergeKeyValues(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		body string
	}{
		{
			name: "merged ide mapping",
			body: `qode_version: 0.1.0
base: &base
  cursor:
    enabled: false
  claude_code:
    enabled: false
ide:
  <<: *base
`,
		},
		{
			name: "merged single ide entry",
			body: `qode_version: 0.1.0
off: &off
  enabled: false
ide:
  cursor:
    <<: *off
`,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			dir := seedConfig(t, tc.body)
			if _, err := Upgrade(context.Background(), dir, "dev"); err != nil {
				t.Fatalf("Upgrade: %v", err)
			}

			var got Config
			if err := yaml.Unmarshal(readConfig(t, dir), &got); err != nil {
				t.Fatalf("unmarshalling upgraded config: %v", err)
			}
			if got.IDE.Cursor.Enabled {
				t.Errorf("a value set through a merge key was overridden by the default:\n%s", readConfig(t, dir))
			}
		})
	}
}

func TestUpgrade_FillsValuelessFile(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		body string
	}{
		{name: "empty", body: ""},
		{name: "comment only", body: "# hand-written\n"},
		{name: "document marker only", body: "---\n"},
		{name: "explicit null", body: "~\n"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			dir := seedConfig(t, tc.body)
			changed, err := Upgrade(context.Background(), dir, "dev")
			if err != nil {
				t.Fatalf("Upgrade: %v", err)
			}
			if !changed {
				t.Fatal("Upgrade reported no change on a file carrying no values")
			}
			// An absent qode_version makes every guarded command report "not
			// initialised", whose remediation is the command that just ran.
			if got := string(readConfig(t, dir)); !strings.Contains(got, "qode_version: dev") {
				t.Errorf("filled file has no qode_version:\n%s", got)
			}
		})
	}
}

func TestUpgrade_RefusesMultipleDocuments(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		body string
	}{
		{name: "well formed second document", body: "qode_version: 0.1.0\n---\nreview:\n  min_code_score: 11\n"},
		// A second document that does not parse is still a second document: dropping
		// it on write loses whatever the user put there.
		{name: "malformed second document", body: "qode_version: 0.1.0\n---\nscoring: [\n"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			dir := seedConfig(t, tc.body)

			changed, err := Upgrade(context.Background(), dir, "dev")
			if !errors.Is(err, ErrConfigInvalid) {
				t.Fatalf("error = %v, want ErrConfigInvalid", err)
			}
			if changed {
				t.Error("Upgrade reported a change for a multi-document file")
			}
			if got := string(readConfig(t, dir)); got != tc.body {
				t.Errorf("multi-document file was modified:\ngot  %q\nwant %q", got, tc.body)
			}
		})
	}
}

func TestUpgrade_ReportsNoWriteOnFailure(t *testing.T) {
	t.Parallel()

	if runtime.GOOS == "windows" {
		t.Skip("directory permissions are not enforced the same way on Windows")
	}
	if os.Geteuid() == 0 {
		t.Skip("root ignores directory permissions")
	}

	dir := seedConfig(t, "qode_version: 0.1.0\n")
	if err := os.Chmod(dir, 0555); err != nil {
		t.Fatalf("chmod: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(dir, 0755) })

	changed, err := Upgrade(context.Background(), dir, "dev")
	if err == nil {
		t.Fatal("expected Upgrade to fail writing into an unwritable directory")
	}
	if changed {
		t.Error("Upgrade reported a write that did not happen")
	}
}

func TestUpgrade_LeavesAliasedVersionAlone(t *testing.T) {
	t.Parallel()

	// Writing into an alias node emits a reference to an anchor that does not
	// exist, leaving a file qode init can never parse again.
	const body = `v: &v 0.1.0
qode_version: *v
`
	dir := seedConfig(t, body)

	if _, err := Upgrade(context.Background(), dir, "100"); err != nil {
		t.Fatalf("Upgrade: %v", err)
	}

	rendered := readConfig(t, dir)
	if strings.Contains(string(rendered), "qode_version: *100") {
		t.Fatalf("aliased qode_version was rewritten into a broken anchor:\n%s", rendered)
	}
	var reparsed Config
	if err := yaml.Unmarshal(rendered, &reparsed); err != nil {
		t.Fatalf("upgraded file no longer parses: %v\n%s", err, rendered)
	}
	if reparsed.QodeVersion != "0.1.0" {
		t.Errorf("qode_version = %q, want the aliased 0.1.0", reparsed.QodeVersion)
	}
}

func TestUpgrade_FlowStyleMappingStaysParseable(t *testing.T) {
	t.Parallel()

	dir := seedConfig(t, "qode_version: 0.1.0\nide: {cursor: {enabled: false}}\n")

	if _, err := Upgrade(context.Background(), dir, "dev"); err != nil {
		t.Fatalf("Upgrade: %v", err)
	}

	rendered := readConfig(t, dir)
	var got Config
	if err := yaml.Unmarshal(rendered, &got); err != nil {
		t.Fatalf("flow-style config no longer parses: %v\n%s", err, rendered)
	}
	if got.IDE.Cursor.Enabled {
		t.Errorf("flow-style enabled: false was overridden:\n%s", rendered)
	}
	if !got.IDE.OpenCode.Enabled {
		t.Errorf("opencode was not appended into the flow-style mapping:\n%s", rendered)
	}
	for _, line := range strings.Split(string(rendered), "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "ide:") && strings.Contains(line, "#") {
			t.Errorf("a comment was rendered inside the flow mapping: %q", line)
		}
	}
}

func TestUpgrade_MergeKeyRendersWithoutExplicitTag(t *testing.T) {
	t.Parallel()

	dir := seedConfig(t, `qode_version: 0.1.0
base: &base
  cursor:
    enabled: false
ide:
  <<: *base
`)

	if _, err := Upgrade(context.Background(), dir, "dev"); err != nil {
		t.Fatalf("Upgrade: %v", err)
	}

	rendered := string(readConfig(t, dir))
	if strings.Contains(rendered, "!!merge") {
		t.Errorf("re-encoded merge key carries an explicit tag no human wrote:\n%s", rendered)
	}
	if !strings.Contains(rendered, "<<: *base") {
		t.Errorf("merge key was not preserved:\n%s", rendered)
	}
}
